# Generated by Django 3.1.2 on 2020-10-22 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='comment_content',
            new_name='reply_content',
        ),
    ]
