# Generated by Django 3.1.2 on 2020-10-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20201022_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='work',
        ),
        migrations.AddField(
            model_name='category',
            name='tag',
            field=models.ManyToManyField(related_name='categories_tags', through='work.CategoryToTag', to='work.Tag'),
        ),
        migrations.AddField(
            model_name='work',
            name='tag',
            field=models.ManyToManyField(related_name='works_tags', through='work.WorkToTag', to='work.Tag'),
        ),
        migrations.AlterField(
            model_name='wallpaperimage',
            name='image_url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='workimage',
            name='image_url',
            field=models.URLField(max_length=1000),
        ),
    ]
