# Generated by Django 3.1.2 on 2020-10-22 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_auto_20201022_2045'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categorytotag',
            unique_together={('category', 'tag')},
        ),
        migrations.AlterUniqueTogether(
            name='worktotag',
            unique_together={('work', 'tag')},
        ),
    ]
