# Generated by Django 3.1.2 on 2020-10-26 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_auto_20201026_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='backgroundcolor',
            new_name='backgroundolor',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='tag',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='tag',
            new_name='tags',
        ),
    ]
