# Generated by Django 3.1.2 on 2020-10-26 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_auto_20201026_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='backgroundolor',
            new_name='backgroundcolor',
        ),
    ]
