# Generated by Django 3.1.2 on 2020-10-27 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0008_auto_20201026_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='tags',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='tags',
            new_name='tag',
        ),
    ]
