# Generated by Django 3.1.2 on 2020-10-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201020_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='short_introduce',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
