# Generated by Django 3.1.2 on 2020-10-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20201020_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='short_introduce',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
