# Generated by Django 3.1.2 on 2020-10-21 17:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20201021_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='short_introduce',
            new_name='introduction',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='profile_image',
            new_name='profile_image_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
