# Generated by Django 3.1.2 on 2020-10-22 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20201022_2045'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'creator')},
        ),
    ]
